config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users,
    controllers:{omniauth_callbacks: "users/omniauth_callbacks"}

  as :user do
    get "signup", to: "devise/registrations#new"
    get "signin", to: "devise/sessions#new"

    post "signup", to: "devise/registrations#create"
    post "signin", to: "devise/sessions#create"

    delete "signout", to: "devise/sessions#destroy"
  end

  resources :users, only: %i(show)

  namespace :admin do
    get "index", to: "courses#index"
    resources :courses, except: :show
    resources :users
    resources :words
    resources :questions
  end

  get "follow/:follow_user_id", to: "users#follow", as: "follow"
  get "unfollow/:unfollow_user_id", to: "users#unfollow", as: "unfollow"
  get "course/:course_id/words", to: "words#index", as: "learn_words"
  get "course/:course_id/do-lesson", to: "lessons#do_lesson", as: "do_lesson"
  get "course/:user_id/:course_id/:result_id/view-result", to: "lessons#view_result", as: "view_result"
  get "word-learned", to: "words#view_word", as: "view_word"
  get "/search", to:"courses#search"

  post "lesson/submit-answer", to: "lessons#submit_answer", as: "submit_answer"
end

app/models/user.rb
class User < ApplicationRecord
  OMNIAUTH_PROVIDERS = %W(#{Settings.omniauth.facebook}
  #{Settings.omniauth.google_oauth2}).freeze
  USER_PARAMS = %i(name email password avatar).freeze

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable,
    :omniauthable, omniauth_providers: OMNIAUTH_PROVIDERS.map(&:to_sym)

  before_create :add_default_avatar, only: %i(create update)

  has_many :courses, dependent: :destroy
  has_many :learnings, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :active_relationships, class_name: Follower.name, foreign_key: "follower_id",dependent: :destroy
  has_many :passive_relationships, class_name: Follower.name, foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  scope :order_by_column, ->(column){order(column)}

  has_one_attached :avatar

  class << self
    def new_with_session params, session
      super.tap do |user|
        OMNIAUTH_PROVIDERS.each do |provider|
          if data = session["devise.#{provider}_data"] &&
              session["devise.#{provider}_data"]["extra"]["raw_info"]
            next unless user.email.blank?
            user.email = data["email"]
            user.
            break
          end
        end
      end
    end

    def from_omniauth auth
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[Settings.user.min_password_length, Settings.user.max_password_length]
        user.name = auth.info.name
      end
    end
  end

  def following? current_user_id, user_id
    Follower.find_by(follower_id: current_user_id, followed_id: user_id).blank?
  end

  def follow other_user
    following << other_user
  end

  def unfollow other_user
    following.delete other_user
  end

  def current_user? user
    self == user
  end

  private

  def add_default_avatar
    unless avatar.attached?
      self.avatar.attach(io: File.open(Rails.root.join("app", "assets", "images", "default.png")), filename: "default.png" , content_type: "image/png")
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :find_user, except: %i(index new create)

  def index
    @users = User.page(params[:page]).per(Settings.user.user_per_page)
      .order_by_column created_at: :desc
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "user.create_success"
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update user_params
      flash[:success] = t "user.edit_success"
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t "user.destroy_success"
    else
      flash[:danger] = t "user.destroy_fail"
    end
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit User::USER_PARAMS
  end

  def find_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t "user.notfound"
    redirect_to admin_index_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    generic_callback Settings.omniauth.facebook
  end

  def google_oauth2
    generic_callback Settings.omniauth.google_oauth2
  end

  def generic_callback provider
    @user = User.from_omniauth request.env["omniauth.auth"]
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, kind: provider.capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user, only: %i(show)

  def show
    @activities = Result.where(user_id: @user.id).includes(:course).page(params[:page])
      .per(Settings.result.result_per_page).order_by_column created_at: :desc
  end

  def follow
    @user = User.find params[:follow_user_id]
    current_user.follow @user
    redirect_to request.referer
  end

  def unfollow
    @user = User.find params[:unfollow_user_id]
    current_user.unfollow @user
    redirect_to request.referer
  end

  private

  def find_user
    @user = User.find_by id: params[:id]
    return if @user
    render file: "#{Rails.root}/public/404", status: :not_found
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="container">
  <div class="row my-2">
    <div class="col-lg-4 order-lg-1 text-center">
      <div class="target">
        <% if @user.avatar.attached?  %>
          <%= image_tag @user.avatar , class: "mx-auto img-fluid img-circle d-block", alt: "avatar" %>
        <% else %>
          <%= image_tag ActionController::Base.helpers.asset_path("default.png") , class: "mx-auto img-fluid img-circle d-block", alt: "avatar" %>
        <% end %>
        <br><label><h4><b><%= @user.name %></b></h4></label>
        <% if current_user.current_user? @user %>
          <%= link_to  edit_user_registration_path do %>
            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
          <% end %>
        <% end %>
        <br>
        <% unless current_user.current_user? @user %>
          <% if current_user.following? current_user.id, @user.id %>
            <%= link_to t("user.Follow"), follow_path(@user.id), class: "btn btn-success" %>
          <% else %>
            <%= link_to t("user.Unfollow"), unfollow_path(@user.id), class: "btn btn-danger" %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-lg-8 order-lg-2">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a href="" data-target="#profile" data-toggle="tab" class="nav-link active"><%= t "user.profile" %></a>
        </li>
      </ul>
      <div class="tab-content py-4">
        <div class="tab-pane active" id="profile">
          <h5 class="mb-3 font-weight-bold"><%= t "user.user_profile" %></h5>
          <div class="row">
            <div class="col-md-6">
              <div class="user-name d-flex">
                <label><%= t "user.name" %>:&nbsp;</label>
                <label>
                  <%= @user.name %>
                </label>
              </div>
              <div class="user-email d-flex">
                <label><%= t "user.email" %>:&nbsp;</label>
                <label>
                <%= @user.email %>
              </label>
              </div>
            </div>
            <div class="col-md-12">
              <h5 class="mt-2 font-weight-bold"><span class="fa fa-clock-o ion-clock float-right"></span><%= t "user.recent_activity" %></h5>
              <table class="table table-sm table-hover table-striped">
                <thead>
                  <th><%= t "courses" %></th>
                  <th><%= t "score" %></th>
                  <th><%= t "date" %></th>
                </thead>
                <tbody>
                <% @activities.each do |ac| %>
                  <tr>
                    <td>
                      <% if current_user.current_user? @user %>
                        <%= link_to view_result_path(params[:id], ac.course_id, ac.id) do%>
                          <%= ac.course_name %>
                        <% end %>
                      <% else %>
                        <%= ac.course_name %>
                      <% end %>
                    </td>
                    <td><%= ac.grade %></td>
                    <td><%= ac.created_at.strftime Settings.date.format %></td>
                  </tr>
                <% end %>
                </tbody>
              </table>
              <%= paginate @activities %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>