config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users,
    controllers:{omniauth_callbacks: "users/omniauth_callbacks"}

  as :user do
    get "signup", to: "devise/registrations#new"
    get "signin", to: "devise/sessions#new"

    post "signup", to: "devise/registrations#create"
    post "signin", to: "devise/sessions#create"

    delete "signout", to: "devise/sessions#destroy"
  end

  resources :users, only: %i(show)

  namespace :admin do
    get "index", to: "courses#index"
    resources :courses, except: :show
    resources :users
    resources :words
    resources :questions
  end

  get "follow/:follow_user_id", to: "users#follow", as: "follow"
  get "unfollow/:unfollow_user_id", to: "users#unfollow", as: "unfollow"
  get "course/:course_id/words", to: "words#index", as: "learn_words"
  get "course/:course_id/do-lesson", to: "lessons#do_lesson", as: "do_lesson"
  get "course/:user_id/:course_id/:result_id/view-result", to: "lessons#view_result", as: "view_result"
  get "word-learned", to: "words#view_word", as: "view_word"
  get "/search", to:"courses#search"

  post "lesson/submit-answer", to: "lessons#submit_answer", as: "submit_answer"
end

app/models/supports/home.rb
class Supports::Home
  attr_reader :user, :page

  def initialize user, page
    @user = user
    @page = page
  end

  def user_followers
    @user.followers.page(@page).per(Settings.user.user_follower_per_page)
      .order_by_column :name
  end

  def user_followed
    @user.following.page(@page).per(Settings.user.user_followed_per_page)
      .order_by_column :name
  end

  def users_high_score
    Result.limit(Settings.user.user_high_score).order_by_column :grade
  end

  def list_courses
    Course.page(@page).per(Settings.course.course_per_page).order_by_column :created_at
  end

  def count_word_learned
    @user.learnings.size
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @supports = Supports::Home.new current_user, params[:page]
  end
end

app/views/home/index.html.erb
<%= provide :title, t("home_page.title") %>
<div class="container-fluid py-3">
  <div class="row">
    <div class="col-12 col-sm-12 col-md-4 user-summary">
      <div id="accordion">
        <div class="card">
          <div class="card-header p-0" id="headingOne">
            <h5 class="mb-0">
              <button class="btn btn-link bg-success text-white d-block w-100" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                <%= t"home_page.Summary" %>
              </button>
            </h5>
          </div>
          <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="card-body">
              <div class="word-memmories"><%= t "home_page.Words_memorised" %>:
                <% if @supports.count_word_learned == Settings.zero_records %>
                  <%= @supports.count_word_learned %>
                <% else %>
                  <%= link_to view_word_path do %>
                    <%= @supports.count_word_learned %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header p-0" id="headingTwo">
            <h5 class="mb-0">
              <button class="btn btn-link bg-success text-white collapsed d-block w-100" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                <%= t "home_page.Follower" %> (<%= @supports.user_followers.size %>):
              </button>
            </h5>
          </div>
          <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
            <div class="card-body">
              <div class="list-follower">
              <% if @supports.user_followers %>
                <% @supports.user_followers.each do |follower| %>
                  <div class="d-inline-block user-follow-item">
                    <div class="d-flex">
                      <span class="avatar">
                        <%= image_tag follower.avatar, class: "rounded-circle mx-2", size: Settings.user.avatar_list_follow %>
                      </span>
                      <%= link_to user_path(follower) do %>
                        <span class="name"><%= follower.name %></span>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header p-0" id="headingThree">
            <h5 class="mb-0">
              <button class="btn btn-link bg-success text-white collapsed d-block w-100" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                <%= t "home_page.Followed" %> (<%= @supports.user_followed.size %>):
              </button>
            </h5>
          </div>
          <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
            <div class="card-body">
              <div class="list-followed">
                <% if @supports.user_followed %>
                  <% @supports.user_followed.each do |followed| %>
                  <div class="d-inline-block user-follow-item">
                    <div class="d-flex">
                      <span class="avatar">
                        <%= image_tag followed.avatar, class: "rounded-circle mx-2", size: Settings.user.avatar_list_follow %>
                      </span>
                      <%= link_to user_path(followed) do %>
                        <span class="name"><%= followed.name %></span>
                      <% end %>
                    </div>
                  </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-sm-12 col-md-8 list-courses">
      <h3 class="heading"><%= t "course.list" %></h3>
      <div class="row">
        <% @supports.list_courses.each do |course| %>
          <div class="card col-12 col-sm-6 col-md-4 py-2">
            <%= image_tag course.image, class: "card-img-top w-100" %>
            <div class="card-body p-0">
              <h5 class="card-title mt-2"><%= course.name %></h5>
              <p class="card-text"><%= course.description %></p>
              <div class="d-flex">
                <%= link_to t("home_page.Word_List"), learn_words_path(course.id), class: "btn btn-success mx-1 w-50" %>
                <%= link_to t("home_page.Start_Lesson"), do_lesson_path(course.id), class: "btn btn-success mx-1 w-50",
                  data:{ confirm: t("lesson.confirm_lesson")}%>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>