config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users,
    controllers:{omniauth_callbacks: "users/omniauth_callbacks"}

  as :user do
    get "signup", to: "devise/registrations#new"
    get "signin", to: "devise/sessions#new"

    post "signup", to: "devise/registrations#create"
    post "signin", to: "devise/sessions#create"

    delete "signout", to: "devise/sessions#destroy"
  end

  resources :users, only: %i(show)

  namespace :admin do
    get "index", to: "courses#index"
    resources :courses, except: :show
    resources :users
    resources :words
    resources :questions
  end

  get "follow/:follow_user_id", to: "users#follow", as: "follow"
  get "unfollow/:unfollow_user_id", to: "users#unfollow", as: "unfollow"
  get "course/:course_id/words", to: "words#index", as: "learn_words"
  get "course/:course_id/do-lesson", to: "lessons#do_lesson", as: "do_lesson"
  get "course/:user_id/:course_id/:result_id/view-result", to: "lessons#view_result", as: "view_result"
  get "word-learned", to: "words#view_word", as: "view_word"
  get "/search", to:"courses#search"

  post "lesson/submit-answer", to: "lessons#submit_answer", as: "submit_answer"
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :word
  has_many :answers, dependent: :destroy

  accepts_nested_attributes_for :answers, allow_destroy: true,
  reject_if: proc{|attributes| attributes[:content].blank?}

  scope :in_words, ->(arr_words_id){where word_id: arr_words_id}
  scope :rand, -> {order("RAND()")}

  QUESTION_PARAMS = [:word_id, :question, :correct_answer,
    answers_attributes: [:id, :content, :_destroy]].freeze

  scope :order_by_column, ->(column){order(column)}
  scope :include_word_name, ->{select "questions.*, words.name as word_name"}
  delegate :name, to: :word, prefix: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < AdminController
  before_action :load_question, only: %i(show edit update destroy)

  def index
    @questions = Question.includes(:word).page(params[:page]).per(Settings.questions.question_per_page)
      .order_by_column :question
  end

  def create
    @question = Question.new questions_params
    if @question.save
      redirect_to admin_questions_path
    else
      flash[:danger] = t "question.create_failed"
      render :new
    end
  end

  def new
    @question = Question.new
  end

  def edit; end

  def update
    if @question.update questions_params
      flash[:success] = t "question.update_success"
      redirect_to admin_questions_path
    else
      render :edit
    end
  end

  def destroy
    if @question.destroy
      flash[:success] = t "question.delete_success"
      redirect_to admin_questions_path
    else
      render :new
    end
  end

  private

  def load_question
    @question = Question.find_by id: params[:id]
    return if @question
    render file: "#{Rails.root}/public/404", status: :not_found
  end

  def questions_params
    params.require(:question).permit Question::QUESTION_PARAMS
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def convert_words
    Word.pluck :name, :id
  end

  def convert_answers question_id
    Answer.where(question_id: question_id).pluck :content, :id
  end
end

app/views/admin/questions/_answer_fields.html.erb
<div class="row fields mb-3">
  <%= f.label :content, t("question.Answer"), class: "mt-2"%>
  <div class="col-md-6">
    <%= f.text_field :content, class: "form-control" %>
    <%= f.hidden_field :_destroy %>
  </div>
  <div class="col-md-2 mt-1">
    <%= link_to "#", onClick: "removeField(this); return false;" do %>
      <i class="fa fa-times" style="color: red; font-size: 30px"></i>
    <% end %>
  </div>
</div>

app/views/admin/questions/_form.html.erb
<%= form_for [:admin, @question] do |f| %>
  <div>
    <%= render "shared/error_messages", object: f.object %>

    <%= f.label :question %>
    <%= f.text_field :question, class: "form-control" %>

    <% if @question.id %>
      <%= f.label :correct_answer %>
      <%= f.select :correct_answer, options_for_select(convert_answers(@question.id), selected: @question.correct_answer), {}, class: "form-control" %>
    <% end %>

    <%= f.label :word_id %>
    <%= f.select :word_id, options_for_select(convert_words, selected: @question.word_id), {}, class: "form-control" %>
    <hr>
    <%= f.fields_for :answers do |builder| %>
      <%= render "admin/questions/answer_fields", f: builder %>
    <% end %>
    <%= link_to_add_fields t("question.Add_answer"), f, :answers %>
  </div>
  <div>
    <%= f.submit yield(:button_text), class: "btn btn-primary my-2" %>
  </div>
<% end %>

app/views/admin/questions/edit.html.erb
<% provide :title, t("question.Edit_question") %>
<% provide :button_text, t("question.Edit") %>
<%= render "form"%>

app/views/admin/questions/index.html.erb
<div class="row">
  <div class="col-12">
    <%= link_to new_admin_question_path, class: "btn btn-primary mb-3" do %>
      <i class="fa fa-plus"></i>
      <%= t "question.Create_question" %>
    <% end %>
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary"><%= t "question.list_question" %></h6>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered w-100"cellspacing="0">
            <tr>
              <th><%= t "question.stt" %></th>
              <th><%= t "question.word_name" %></th>
              <th><%= t "question.name" %></th>
              <th><%= t "question.action" %></th>
            </tr>
            <% stt = get_stt params[:page].to_i, Settings.questions.question_per_page %>
            <% @questions.each do |question| %>
            <tr>
              <td class="stt text-center"><%= stt %></td>
              <td><%= question.word_name %></td>
              <td><%= question.question %></td>
              <td>
                <%= link_to admin_question_path(question) do %>
                  <i class="fa fa-eye"></i>
                <% end %>
                <%= link_to edit_admin_question_path(question) do %>
                  <i class="fa fa-edit"></i>
                <% end %>
                <%= link_to [:admin, question], method: "delete", data: {confirm: t("question.are_you_sure")} do %>
                  <i class="fa fa-trash"></i>
                <% end %>
              </td>
            </tr>
            <% stt += 1 %>
            <% end %>
          </table>
          <div class="pagination">
            <%= paginate @questions %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/questions/new.html.erb
<% provide :title, t("question.Add_question") %>
<% provide :button_text, t("question.Add") %>
<%= render "form"%>