config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users,
    controllers:{omniauth_callbacks: "users/omniauth_callbacks"}

  as :user do
    get "signup", to: "devise/registrations#new"
    get "signin", to: "devise/sessions#new"

    post "signup", to: "devise/registrations#create"
    post "signin", to: "devise/sessions#create"

    delete "signout", to: "devise/sessions#destroy"
  end

  resources :users, only: %i(show)

  namespace :admin do
    get "index", to: "courses#index"
    resources :courses, except: :show
    resources :users
    resources :words
    resources :questions
  end

  get "follow/:follow_user_id", to: "users#follow", as: "follow"
  get "unfollow/:unfollow_user_id", to: "users#unfollow", as: "unfollow"
  get "course/:course_id/words", to: "words#index", as: "learn_words"
  get "course/:course_id/do-lesson", to: "lessons#do_lesson", as: "do_lesson"
  get "course/:user_id/:course_id/:result_id/view-result", to: "lessons#view_result", as: "view_result"
  get "word-learned", to: "words#view_word", as: "view_word"
  get "/search", to:"courses#search"

  post "lesson/submit-answer", to: "lessons#submit_answer", as: "submit_answer"
end

app/views/layouts/_admin_navbar.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
    <div class="input-group">
      <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-primary" type="button">
          <i class="fa fa-search fa-sm"></i>
        </button>
      </div>
    </div>
  </form>

  <ul class="navbar-nav ml-auto">
    <div class="topbar-divider d-none d-sm-block"></div>
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.name %></span>
        <%= image_tag current_user.avatar, class: "img-profile rounded-circle w-100" %>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <%= link_to root_path, class: "dropdown-item" do %>
          <i class="fa fa-home fa-sm fa-fw mr-2 text-black-400"></i>
          <%= t "home_page.title" %>
        <% end %>
        <%= link_to user_path(current_user), class: "dropdown-item" do %>
          <i class="fa fa-user fa-sm fa-fw mr-2 text-black-400"></i>
          <%= t "header.Profile" %>
        <% end %>
        <div class="dropdown-divider"></div>
        <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
          <i class="fa fa-sign-out fa-sm fa-fw mr-2 text-black-400"></i>
          <%= t("header.Sign_out") %>
        <% end %>
      </div>
    </li>
  </ul>
</nav>

app/views/layouts/_admin_sidebar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fa fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3"><%= t "header.Admin_panel" %><sup>2</sup></div>
      </a>

      <hr class="sidebar-divider my-0">

      <li class="nav-item active">
        <a class="nav-link" href="index.html">
          <i class="fa fa-fw fa-tachometer-alt"></i>
          <label><%= t "dashboard" %></label></a>
      </li>

      <hr class="sidebar-divider">

      <div class="sidebar-heading">
      </div>

      <li class="nav-item">
        <%= link_to admin_users_path, class: "nav-link collapsed" do %>
          <i class="fa fa-fw fa-user"></i>
          <label><%= t "users" %></label>
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to admin_courses_path, class: "nav-link collapsed" do %>
          <i class="fa fa-fw fa-cog"></i>
          <label><%= t"courses" %></label>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to admin_words_path, class: "nav-link" do %>
          <i class="fa fa-fw fa-file-word-o"></i>
          <label><%= t "word.Manage_words" %></label>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to admin_questions_path, class: "nav-link" do %>
          <i class="fa fa-fw fa-question-circle"></i>
          <label><%= t "question.Manage_questions" %></label>
        <% end %>
      </li>
    </ul>

app/views/layouts/_front_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to t("header.title"), root_url, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%= form_for :q, url: search_path, method: :get, html: {class: "form-inline my-2 my-lg-0"} do |f| %>
      <%= f.search_field :name_or_description_cont, class: "form-control mr-sm-2", placeholder: " #{t "search_course"}" %>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><%= t"header.Search" %></button>
    <% end %>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.name %></span>
          <%= image_tag current_user.avatar, class: "img-profile rounded-circle w-100" %>
        </a>
        <div class="dropdown-menu dropdown-menu-user" aria-labelledby="navbarDropdown">
          <% if current_user.is_admin? %>
            <%= link_to admin_index_path, class: "dropdown-item" do %>
              <i class="fa fa-external-link fa-sm fa-fw mr-2 text-black-400"></i>
              <%= t "header.Admin_panel" %>
            <% end %>
          <% end %>
          <%= link_to user_path(current_user), class: "dropdown-item" do %>
            <i class="fa fa-user fa-sm fa-fw mr-2 text-black-400"></i>
            <%= t "header.Profile" %>
          <% end %>
          <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
            <i class="fa fa-sign-out fa-sm fa-fw mr-2 text-black-400"></i>
            <%= t("header.Sign_out") %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_scroll_top.html.erb
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fa fa-angle-up"></i>
</a>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body id="page-top">
    <div id="wrapper">
      <%= render "layouts/admin_sidebar" %>
      <div id="content-wrapper" class="d-flex flex-column">
        <div id="content">
          <%= render "layouts/admin_navbar" %>
            <% flash.each do |message_type, message| %>
              <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
            <div class="container-fluid">
              <%= yield %>
            </div>
        </div>
      </div>
    </div>
    <%= render "layouts/scroll_top" %>
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"><%= t "Ready_to_leave" %></h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body"><%= t "modal_logout.Select_logout_below" %></div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal"><%= t "modal_logout.Cancel" %></button>
          <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
            <%= t "modal_logout.Logout" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
  <%= render "layouts/front_nav" if user_signed_in? %>
  <%= yield %>
  </body>
</html>